name: "QQE Test Suite disabled test analyser"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Build Quarkus App with Maven
        run: |
          cd disabled-tests-inspector
          mvn quarkus:dev -DrepoOwner=quarkus-qe -DrepoName=quarkus-test-suite -Dbranches="main" -DoutputFile=disabled-tests-ts.json
      - name: Archive JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: disabled-tests-report
          path: disabled-tests-inspector/disabled-tests-ts.json
          retention-days: 7
